import { z } from "zod";

export const shopDraftSchema = z.object({
  id: z.string().optional(),
  name: z.string().min(1),
  clientId: z.string().min(1),
  apiKey: z.string().optional(),
  ossAccessKeyId: z.string().optional(),
  ossAccessKeySecret: z.string().optional(),
  ossBucket: z.string().optional(),
  ossEndpoint: z.string().optional(),
  ossPublicDomain: z.string().url().optional().or(z.literal("")),
  enabled: z.boolean(),
});

export const appSettingsSchema = z.object({
  defaultSourceRoot: z.string(),
  defaultOutputRoot: z.string(),
  baiduCookie: z.string(),
  watermarkPath: z.string(),
  contentRoot: z.string(),
  uploadExcelPath: z.string(),
  uploadMaxItems: z.number().int().min(1).max(10000),
  listedUpdateMaxWorkers: z.number().int().min(1).max(16),
  imageProvider: z.string(),
  textProvider: z.string(),
  imageBaseUrl: z.string(),
  textBaseUrl: z.string(),
  imageModel: z.string(),
  textModel: z.string(),
  maxWorkers: z.number().int().min(1).max(16),
  maxFolders: z.number().int().min(0),
  exportExcel: z.boolean(),
  convertOriginals: z.boolean(),
  generateCopy: z.boolean(),
  quality: z.string(),
  sceneSourceRoot: z.string(),
  sceneOutputRoot: z.string(),
  sceneMockupRoot: z.string(),
  sceneSingleImage: z.string(),
  sceneAspectRatio: z.string(),
  sceneCount: z.number().int().min(1).max(100),
  sceneMaxWorkers: z.number().int().min(1).max(16),
  sceneMaxFolders: z.number().int().min(0),
  sceneSizeLabel: z.string(),
  scenePromptTemplate: z.string(),
  imagePromptTemplate: z.string(),
  titlePromptTemplate: z.string(),
  descriptionPromptTemplate: z.string(),
  selectedTemplateName: z.string(),
});
